### ISSUE TITLE
Consider better CLI startup command

### ISSUE THREAD

**Issue by pavkriz** [r-bruha/nette-generator#3]
Consider better CLI startup command instead of `php.exe /path/to/project/vendor/r-bruha/nette-generator/index.php`

Options:
1. (probably better) prepare scripts (*nix/win) into `bin` folder of the generator, in same way as Doctrine ([Setting up the Commandline Tool](http://doctrine-orm.readthedocs.org/en/latest/reference/configuration.html#setting-up-the-commandline-tool)) and Cake's Bake ([Installing CakePHP with Composer](http://book.cakephp.org/2.0/en/installation/advanced-installation.html#installing-cakephp-with-composer)) do
2. (maybe too "proprietary") use [Composer's custom command](https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands)

**Comment by r-bruha** [comment]
Added bin folder with prepared run scripts.
