### ISSUE TITLE
Primary key is sometimes not detected or passed into template

### ISSUE THREAD

**Issue by pavkriz** [r-bruha/nette-generator#5]
Primary key is sometimes not detected (when reverse-engineering schema from MySQL) or passed into template (?) resulting into empty property error `$i->` in template, eg. this line:
```
<a class='btn btn-xs btn-warning' n:href='change $i->, $target, link => $presenter->storeRequest()'>{_change}</a>
```

**Comment by r-bruha** [comment]
Fixed, tables without primary key are automatically skipped now.
